import { SyncStats, CachedProblem } from '../types';

/**
 * Service responsible for generating clean markdown dashboard indexes for synchronized LeetCode solutions.
 */
export class ReadmeGenerator {
  /**
   * Formats a Unix epoch timestamp in milliseconds to YYYY-MM-DD UTC string.
   */
  private static formatDate(timestampMs: number): string {
    if (!timestampMs || timestampMs <= 0) return 'Unknown';
    const d = new Date(timestampMs);
    const year = d.getUTCFullYear();
    const month = String(d.getUTCMonth() + 1).padStart(2, '0');
    const day = String(d.getUTCDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  /**
   * Formats difficulty string into clean text.
   */
  private static formatDifficulty(diff: 'Easy' | 'Medium' | 'Hard'): string {
    return diff;
  }

  /**
   * Generates the complete README.md markdown content.
   */
  public static generate(stats: SyncStats, cache: Record<string, CachedProblem>): string {
    const problems = Object.values(cache || {}).filter((p): p is CachedProblem => Boolean(p && p.problemNumber && p.titleSlug));
    
    // Sort ascending by problem number
    problems.sort((a, b) => {
      const numA = parseInt(a.problemNumber || '0', 10);
      const numB = parseInt(b.problemNumber || '0', 10);
      if (!isNaN(numA) && !isNaN(numB)) {
        return numA - numB;
      }
      return (a.problemNumber || '').localeCompare(b.problemNumber || '');
    });

    let md = '# LeetCode Solutions & Synchronization Index\n\n';
    md += 'This repository dashboard is automatically maintained and updated by LeetCommit.\n\n';
    
    md += '## Solved Statistics\n\n';
    md += '| Total Solved | Easy | Medium | Hard |\n';
    md += '| :---: | :---: | :---: | :---: |\n';
    md += `| **${stats.totalSolved}** | ${stats.easyCount} | ${stats.mediumCount} | ${stats.hardCount} |\n\n`;

    md += '## Synchronized Problem Directory\n\n';
    md += '| # | Problem Title | Difficulty | Last Updated |\n';
    md += '| :---: | :--- | :---: | :---: |\n';

    if (problems.length === 0) {
      md += '| - | No solutions synced yet | - | - |\n';
    } else {
      for (const prob of problems) {
        const paddedNum = prob.problemNumber.padStart(4, '0');
        const titleFormatted = prob.titleSlug
          .split('-')
          .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
          .join(' ');
        const url = `https://leetcode.com/problems/${prob.titleSlug}/`;
        const diffStr = this.formatDifficulty(prob.difficulty);
        const dateStr = this.formatDate(prob.lastUpdated);

        md += `| ${paddedNum} | [${titleFormatted}](${url}) | ${diffStr} | ${dateStr} |\n`;
      }
    }

    md += '\n## How to Use\n\n';
    md += '1. Install LeetCommit Chrome Extension.\n';
    md += '2. Configure GitHub Token and Repository URL in Settings.\n';
    md += '3. Submit any passing solution on LeetCode. Your code and problem description will automatically upload directly to this repository!\n';

    md += '\n---\n*Generated by LeetCommit Chrome Extension*';
    return md;
  }
}
